// packages/react/src/components/SymbolKeyboard.tsx
import type { KeyEvent } from '../types'
import { createKeyRepeater } from '@crispychicken/zh-keyboard-core'
import React, { useEffect, useMemo, useRef, useState } from 'react'
import lockOpenIconUrl from '../assets/icons/lock-open-outline.svg'
import lockClosedIconUrl from '../assets/icons/lock-outline.svg'
import '../styles/SymbolKeyboard.scss'

interface SymbolKeyboardProps {
  onKey: (payload: KeyEvent) => void
  onExit: () => void
}

const SymbolKeyboard: React.FC<SymbolKeyboardProps> = ({ onKey, onExit }) => {
  const enSymbolStr = '!@#$%^&*(){}[]<>/\\|:;"\',.?+-=_~`€£¥₹©®™°'
  const zhSymbolStr = '！＠＃￥％…＆＊（）｛｝［］＜＞／＼｜：；＂＇，。？＋－＝＿～·€£¥₹©®™°'
  const [symbolType, setSymbolType] = useState('en')
  const currentSymbolStr = useMemo(() => (symbolType === 'zh' ? zhSymbolStr : enSymbolStr), [symbolType])
  const [isLocked, setIsLocked] = useState(false)

  const repeaterRef = useRef(createKeyRepeater())

  useEffect(() => {
    return () => {
      repeaterRef.current.stop()
    }
  }, [])

  function handleKeyPress(key: string) {
    onKey({ key })
    if (!isLocked) {
      onExit()
    }
  }

  function goBack() {
    onExit()
  }

  function toggleLock() {
    setIsLocked(!isLocked)
  }

  function startRepeat(e: React.PointerEvent, action: () => void) {
    e.preventDefault()
    ;(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId)
    repeaterRef.current.start(action)
  }

  function stopRepeat() {
    repeaterRef.current.stop()
  }

  function pressOnce(e: React.PointerEvent, action: () => void) {
    e.preventDefault()
    action()
  }

  function preventContextMenu(e: React.MouseEvent) {
    e.preventDefault()
  }

  return (
    <div className="symbol-keyboard">
      <div className="symbol-keyboard__content">
        <div className="symbol-keyboard__functions">
          <div className="symbol-keyboard__lang-selector">
            <button
              type="button"
              className={`symbol-keyboard__lang-btn ${
                symbolType === 'zh' ? 'symbol-keyboard__lang-btn--active' : ''
              }`}
              onClick={() => setSymbolType('zh')}
              onContextMenu={preventContextMenu}
            >
              中文
            </button>
            <button
              className={`symbol-keyboard__lang-btn ${
                symbolType === 'en' ? 'symbol-keyboard__lang-btn--active' : ''
              }`}
              onClick={() => setSymbolType('en')}
              onContextMenu={preventContextMenu}
            >
              英文
            </button>
          </div>
          <div className="symbol-keyboard__control-group">
            <button
              className={`symbol-keyboard__key symbol-keyboard__key--function symbol-keyboard__key--lock ${
                isLocked ? 'symbol-keyboard__key--locked' : ''
              }`}
              onClick={toggleLock}
              onContextMenu={preventContextMenu}
            >
              {!isLocked
                ? (
                    <img src={lockOpenIconUrl} alt="Lock open" />
                  )
                : (
                    <img src={lockClosedIconUrl} alt="Lock closed" />
                  )}
            </button>
            <button
              className="symbol-keyboard__key symbol-keyboard__key--function symbol-keyboard__key--back"
              onClick={goBack}
              onContextMenu={preventContextMenu}
            >
              返回
            </button>
          </div>
        </div>

        <div className="symbol-keyboard__symbols-container">
          <div className="symbol-keyboard__symbols-grid">
            {currentSymbolStr.split('').map(char => (
              <button
                key={`key-${char}`}
                className="symbol-keyboard__key"
                onPointerDown={(e) => {
                  if (!isLocked) {
                    pressOnce(e, () => handleKeyPress(char))
                    return
                  }
                  startRepeat(e, () => handleKeyPress(char))
                }}
                onPointerUp={stopRepeat}
                onPointerLeave={stopRepeat}
                onPointerCancel={stopRepeat}
                onContextMenu={preventContextMenu}
              >
                {char}
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

export default SymbolKeyboard

// packages/vue/src/components/SymbolKeyboard.vue
<script setup lang="ts">
import type { KeyEvent } from '../types'
import { createKeyRepeater } from '@crispychicken/zh-keyboard-core'
import { computed, onBeforeUnmount, ref } from 'vue'
import lockOpenIconUrl from '../assets/icons/lock-open-outline.svg'
import lockClosedIconUrl from '../assets/icons/lock-outline.svg'
import '../styles/SymbolKeyboard.scss'

const emit = defineEmits<{
  (e: 'key', payload: KeyEvent): void
  (e: 'exit'): void
}>()

const enSymbolStr = '!@#$%^&*(){}[]<>/\\|:;"\',.?+-=_~`€£¥₹©®™°'
const zhSymbolStr = '！＠＃￥％…＆＊（）｛｝［］＜＞／＼｜：；＂＇，。？＋－＝＿～·€£¥₹©®™°'
const symbolType = ref('en')
const currentSymbolStr = computed(() => symbolType.value === 'zh' ? zhSymbolStr : enSymbolStr)
const isLocked = ref(false)

const repeater = createKeyRepeater()

function startRepeat(e: PointerEvent, action: () => void) {
  e.preventDefault()
  ;(e.currentTarget as HTMLElement | null)?.setPointerCapture?.(e.pointerId)
  repeater.start(action)
}

function stopRepeat() {
  repeater.stop()
}

onBeforeUnmount(() => {
  repeater.stop()
})

function onSymbolDown(char: string, e: PointerEvent) {
  // 未锁定时会自动退出，长按连发没有意义；保持单次输入。
  if (!isLocked.value) {
    e.preventDefault()
    handleKeyPress(char)
    return
  }
  startRepeat(e, () => handleKeyPress(char))
}

function handleKeyPress(key: string) {
  emit('key', { key })
  if (!isLocked.value) {
    emit('exit')
  }
}

function goBack() {
  emit('exit')
}

function setSymbolType(type: 'zh' | 'en') {
  symbolType.value = type
}

function toggleLock() {
  isLocked.value = !isLocked.value
}
</script>

<template>
  <div class="symbol-keyboard">
    <div class="symbol-keyboard__content">
      <div class="symbol-keyboard__functions">
        <div class="symbol-keyboard__lang-selector">
          <button
            class="symbol-keyboard__lang-btn"
            :class="{ 'symbol-keyboard__lang-btn--active': symbolType === 'zh' }"
            @click="setSymbolType('zh')"
            @contextmenu.prevent
          >
            中文
          </button>
          <button
            class="symbol-keyboard__lang-btn"
            :class="{ 'symbol-keyboard__lang-btn--active': symbolType === 'en' }"
            @click="setSymbolType('en')"
            @contextmenu.prevent
          >
            英文
          </button>
        </div>
        <div class="symbol-keyboard__control-group">
          <button
            class="symbol-keyboard__key symbol-keyboard__key--function symbol-keyboard__key--lock"
            :class="{ 'symbol-keyboard__key--locked': isLocked }"
            @click="toggleLock"
            @contextmenu.prevent
          >
            <img v-if="!isLocked" :src="lockOpenIconUrl" alt="Lock open" />
            <img v-else :src="lockClosedIconUrl" alt="Lock closed" />
          </button>
          <button
            class="symbol-keyboard__key symbol-keyboard__key--function symbol-keyboard__key--back"
            @click="goBack"
            @contextmenu.prevent
          >
            返回
          </button>
        </div>
      </div>

      <div class="symbol-keyboard__symbols-container">
        <div class="symbol-keyboard__symbols-grid">
          <button
            v-for="(char, index) in currentSymbolStr"
            :key="`key-${index}`"
            class="symbol-keyboard__key"
            @pointerdown="(e) => onSymbolDown(char, e)"
            @pointerup="stopRepeat"
            @pointerleave="stopRepeat"
            @pointercancel="stopRepeat"
            @contextmenu.prevent
          >
            {{ char }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
